<?php

namespace ContainerN4O9tpk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YSlX6XrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ySlX6Xr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ySlX6Xr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mesaRepository' => ['privates', 'App\\Repository\\MesaRepository', 'getMesaRepositoryService', true],
            'restaurante' => ['privates', '.errored..service_locator.ySlX6Xr.App\\Entity\\Restaurante', NULL, 'Cannot autowire service ".service_locator.ySlX6Xr": it needs an instance of "App\\Entity\\Restaurante" but this type has been excluded in "config/services.yaml".'],
        ], [
            'mesaRepository' => 'App\\Repository\\MesaRepository',
            'restaurante' => 'App\\Entity\\Restaurante',
        ]);
    }
}
