<?php

namespace ContainerN4O9tpk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMesaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MesaController' shared autowired service.
     *
     * @return \App\Controller\MesaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'MesaController.php';

        $container->services['App\\Controller\\MesaController'] = $instance = new \App\Controller\MesaController();

        $instance->setContainer(($container->privates['.service_locator.7CWlFZt'] ?? $container->load('get_ServiceLocator_7CWlFZtService'))->withContext('App\\Controller\\MesaController', $container));

        return $instance;
    }
}
