<?php

namespace ContainerN4O9tpk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpinionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.K3FFIS0.App\Entity\Opinion' shared service.
     *
     * @return \App\Entity\Opinion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.K3FFIS0": it needs an instance of "App\\Entity\\Opinion" but this type has been excluded in "config/services.yaml".');
    }
}
