<?php

namespace ContainerN4O9tpk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3DipYnt.App\Entity\Reserva' shared service.
     *
     * @return \App\Entity\Reserva
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3DipYnt": it needs an instance of "App\\Entity\\Reserva" but this type has been excluded in "config/services.yaml".');
    }
}
