<?php

namespace ContainerN4O9tpk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestauranteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tqU9Hn6.App\Entity\Restaurante' shared service.
     *
     * @return \App\Entity\Restaurante
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tqU9Hn6": it needs an instance of "App\\Entity\\Restaurante" but this type has been excluded in "config/services.yaml".');
    }
}
