<?php

namespace ContainerSq5nMe1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MMB7_7FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MMB7.7F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MMB7.7F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservaRepository' => ['privates', 'App\\Repository\\ReservaRepository', 'getReservaRepositoryService', true],
            'reservas' => ['privates', '.errored..service_locator.MMB7.7F.App\\Entity\\Reserva', NULL, 'Cannot autowire service ".service_locator.MMB7.7F": it needs an instance of "App\\Entity\\Reserva" but this type has been excluded in "config/services.yaml".'],
        ], [
            'reservaRepository' => 'App\\Repository\\ReservaRepository',
            'reservas' => 'App\\Entity\\Reserva',
        ]);
    }
}
