<?php

namespace ContainerSq5nMe1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PtkVROFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ptkVROF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ptkVROF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'restauranteRepository' => ['privates', 'App\\Repository\\RestauranteRepository', 'getRestauranteRepositoryService', true],
        ], [
            'restauranteRepository' => 'App\\Repository\\RestauranteRepository',
        ]);
    }
}
