<?php

namespace ContainerSq5nMe1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tk7uWKBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Tk7uWKB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Tk7uWKB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'correo' => ['privates', 'App\\Service\\Correo', 'getCorreoService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'mailerController' => ['services', 'App\\Controller\\MailerController', 'getMailerControllerService', true],
            'mesaRepository' => ['privates', 'App\\Repository\\MesaRepository', 'getMesaRepositoryService', true],
            'reservaRepository' => ['privates', 'App\\Repository\\ReservaRepository', 'getReservaRepositoryService', true],
        ], [
            'correo' => 'App\\Service\\Correo',
            'entityManager' => '?',
            'mailer' => '?',
            'mailerController' => 'App\\Controller\\MailerController',
            'mesaRepository' => 'App\\Repository\\MesaRepository',
            'reservaRepository' => 'App\\Repository\\ReservaRepository',
        ]);
    }
}
