<?php

namespace ContainerSq5nMe1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCorreoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Correo' shared autowired service.
     *
     * @return \App\Service\Correo
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Correo.php';

        $a = ($container->services['App\\Service\\Pdf'] ?? $container->load('getPdfService'));

        if (isset($container->privates['App\\Service\\Correo'])) {
            return $container->privates['App\\Service\\Correo'];
        }
        $b = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\Correo'])) {
            return $container->privates['App\\Service\\Correo'];
        }

        return $container->privates['App\\Service\\Correo'] = new \App\Service\Correo($a, $b);
    }
}
